characters/urls.py
from django.urls import path 
from characters.views import *

app_name = "characters"
urlpatterns = [
    path("<int:folder>/add/", AddCharacterView.as_view(), name="add"),
    path("<int:pk>/view/", DisplayCharacterView.as_view(), name="view"),
    path("<int:pk>/edit/", EditCharacterView.as_view(), name="edit"),
    path('<int:pk>/delete/', DeleteCharacterView.as_view(), name="delete")
]

folders/urls.py
from django.urls import path
from folders.views import *

app_name = "folders"
urlpatterns = [
    path("<int:parent>/add/", AddFolderView.as_view(), name="add"),
    path("<int:pk>/view/", DisplayFolderView.as_view(), name="view"),
    path("<int:pk>/edit/", EditFolderView.as_view(), name="edit"),
    path("<int:pk>/delete/", DeleteFolderView.as_view(), name="delete")
]

mytoyhouse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

def landing(request):
    return redirect('accounts:login')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing, name='landing'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('folders/', include('folders.urls', namespace='folders')),
    path('characters/', include('characters.urls', namespace='characters'))
]

characters/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from folders.models import Folder

# Create your models here.
class Character(models.Model):
    owner = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_created=True, default=timezone.now)
    folder = models.ForeignKey(Folder, null=False, on_delete=models.CASCADE)

    # basics
    name = models.CharField(max_length=200, null=False)
    nicknames = models.CharField(max_length=200, null=True, blank=True)
    age = models.PositiveIntegerField(null=True, blank=True)
    sex = models.CharField(max_length=20, null=True, blank=True)
    gender = models.CharField(max_length=20, null=True, blank=True)
    description = models.CharField(max_length=200, null=True, blank=True)
    religion = models.CharField(max_length=100, null=True, blank=True)
    race = models.CharField(max_length=100, null=True, blank=True)
    species = models.CharField(max_length=100, null=True, blank=True)

    # birth related
    birthday = models.DateField(null=True, blank=True)
    birthplace = models.CharField(max_length=200, null=True, blank=True)

    # physical descriptions
    blood_type = models.CharField(max_length=5, null=True, blank=True)
    height = models.DecimalField(decimal_places=2, max_digits=10, null=True, blank=True)  # in meters
    weight = models.DecimalField(decimal_places=2, max_digits=10, null=True, blank=True)  # in kilograms
    eye_colour = models.CharField(max_length=50, null=True, blank=True)
    hair_colour = models.CharField(max_length=50, null=True, blank=True)
    eyesight = models.CharField(max_length=50, null=True, blank=True)
    handedness = models.CharField(max_length=20, null=True, blank=True)
    voice = models.CharField(max_length=100, null=True, blank=True)
    physical_description = models.CharField(max_length=2000, null=True, blank=True)
    clothing = models.CharField(max_length=2000, null=True, blank=True)

    # history
    medical_history = models.CharField(max_length=2000, null=True, blank=True)
    criminal_record = models.CharField(max_length=2000, null=True, blank=True)
    education = models.CharField(max_length=2000, null=True, blank=True)
    forming_events = models.CharField(max_length=2000, null=True, blank=True)
    romance = models.CharField(max_length=2000, null=True, blank=True)  # sex life? previous marriages?
    relationships = models.CharField(max_length=2000, null=True, blank=True)
    employment = models.CharField(max_length=2000, null=True, blank=True)  # employment history and current job
    pets = models.CharField(max_length=2000, null=True, blank=True)

    # personality
    hopes_and_dreams = models.CharField(max_length=2000, null=True, blank=True)
    fears = models.CharField(max_length=2000, null=True, blank=True)
    hobbies = models.CharField(max_length=2000, null=True, blank=True)
    likes = models.CharField(max_length=2000, null=True, blank=True)
    dislikes = models.CharField(max_length=2000, null=True, blank=True)
    personality = models.CharField(max_length=2000, null=True, blank=True)

    # misc
    skills = models.CharField(max_length=3000, null=True, blank=True)  # skills? superpowers?
    weaknesses = models.CharField(max_length=3000, null=True, blank=True)
    private = models.BooleanField(null=False, default=False)  # whether other people can view this character

    def __str__(self):
        return self.name
    
    def list_tags(self):
        # return a list of this character's tags as list of strings
        return list(map(str, self.tag_set.all()))


class Tag(models.Model):
    character = models.ForeignKey(Character, on_delete=models.CASCADE)
    tag = models.CharField(max_length=100, null=False)

    def __str__(self):
        return self.tag

characters/forms/CharacterForm.py
from django import forms
from characters.models import Character 

class CharacterForm(forms.ModelForm):
    tags = forms.CharField(max_length=2000, required=False)  # comma-separated string of tags that will be processed
    class Meta:
        model = Character 
        exclude = ["owner", "created"]

characters/views/AddCharacterView.py
from django.views.generic.edit import CreateView
from folders.models import Folder
from characters.models import Tag
from characters.forms import CharacterForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404

class AddCharacterView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy("accounts:login")
    template_name = "characters/add.html"
    form_class = CharacterForm

    def get(self, request, folder):
        # user must be the owner of the target folder
        folder = get_object_or_404(Folder, id=folder)
        if folder.owner != request.user:
            return HttpResponseForbidden()
        
        return super().get(request, folder)
    
    def post(self, request, folder):
        # user must be the owner
        folder = get_object_or_404(Folder, id=folder)
        if folder.owner != request.user:
            return HttpResponseForbidden()
        
        return super().post(request, folder)

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["folder"] = self.kwargs["folder"]
        return data

    def get_success_url(self) -> str:
        return reverse_lazy("characters:view", kwargs={"pk": self.get_form().instance.id})

    def form_valid(self, form):
        form.instance.owner = self.request.user
        data = super().form_valid(form)  # save the character
        
        # process the tags
        tags = list(map(str.strip, form.cleaned_data["tags"].split(',')))
        for tag in tags:
            if tag == '':
                continue  # this happens if initial tags is blank
            
            new_tag = Tag.objects.create(character=form.instance, tag=tag)
            new_tag.save()

        return data
    
    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        # exclude the root folder; no characters in the root folder
        form.fields["folder"].queryset = self.request.user.folder_set.exclude(parent=None)
        form.fields["folder"].initial = self.request.user.folder_set.get(id=self.kwargs["folder"])
        return form

characters/views/DeleteCharacterView.py
from django.views.generic.edit import DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404
from characters.models import Character


class DeleteCharacterView(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy("accounts:login")
    model = Character
    template_name = "characters/view.html"
    context_object_name = "char"

    def get_success_url(self):
        return reverse_lazy("folders:view", kwargs={"pk": self.get_object().folder.id})

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["delete_confirmation"] = True
        return data

    def get(self, request, pk):
        char = get_object_or_404(Character, id=pk)

        # check ownership
        if char.owner != request.user:
            return HttpResponseForbidden()
        return super().get(request, pk)

    def post(self, request, pk):
        char = get_object_or_404(Character, id=pk)

        # check ownership
        if char.owner != request.user:
            return HttpResponseForbidden()
        return super().post(request, pk)

characters/views/DisplayCharacterView.py
from django.views.generic.detail import DetailView
from characters.models import Character
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import HttpResponseForbidden, HttpResponseNotAllowed

class DisplayCharacterView(LoginRequiredMixin, DetailView):
    login_url = reverse_lazy("accounts:login")
    template_name = "characters/view.html"
    context_object_name = "char"
    model = Character

    def get(self, request, pk):
        # private?
        char = self.get_object()
        if char.owner != request.user and char.private:
            return HttpResponseForbidden()
        
        return super().get(request, pk)
    
    def post(self, request, pk):
        return HttpResponseNotAllowed(("GET"))

characters/views/EditCharacterView.py
from django.views.generic.edit import UpdateView
from characters.models import Tag, Character
from characters.forms import CharacterForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import HttpResponseForbidden

class EditCharacterView(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy("accounts:login")
    template_name = "characters/edit.html"
    form_class = CharacterForm
    model = Character
    context_object_name = "char"

    def get(self, request, pk):
        # user must be the owner of the character
        char = self.get_object()
        if char.owner != request.user:
            return HttpResponseForbidden()
        
        return super().get(request, pk)
    
    def post(self, request, pk):
        # user must be the owner of the character
        char = self.get_object()
        if char.owner != request.user:
            return HttpResponseForbidden()
        
        return super().post(request, pk)

    def get_success_url(self) -> str:
        return reverse_lazy("characters:view", kwargs={"pk": self.get_form().instance.id})

    def form_valid(self, form):
        form.instance.owner = self.request.user
        data = super().form_valid(form)  # save the character
        
        # process the tags
        new_tags = list(map(str.strip, form.cleaned_data["tags"].split(',')))  # tags in form
        current_tags = form.instance.list_tags()  # current tags already applied

        # find tags to delete (in current_tags but not tags)
        to_delete = [tag for tag in current_tags if tag not in new_tags]

        # find tags to add (in tags but not current_tags)
        to_add = [tag.strip() for tag in new_tags if (tag not in current_tags) and (tag != '')]

        for tag in to_add:
            new_tag = Tag.objects.create(character=form.instance, tag=tag)
            new_tag.save()

        for tag in to_delete:
            old_tag = Tag.objects.get(character=form.instance, tag=tag)
            old_tag.delete()

        return data
    
    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        # exclude the root folder; no characters in the root folder
        form.fields["folder"].queryset = self.request.user.folder_set.exclude(parent=None)
        form.fields["folder"].initial = form.instance.folder

        # get all the character's current tags
        tags = form.instance.list_tags()
        form.fields["tags"].initial = ", ".join(tags)

        return form

characters/templates/characters/add.html
{% extends "base.html" %} 

{% block main %} 
<h1>Create new character</h1>
<form action="{% url 'characters:add' folder%}" method="POST" class="w-25 mx-auto">
    {% csrf_token %} 
    {% include 'characters/form.html' with form=form %}
    <input type="submit" value="Create">
</form>
{% endblock %}

characters/templates/characters/edit.html
{% extends "base.html" %} 

{% block main %} 
<h1>Edit character</h1>
<form action="{% url 'characters:edit' char.id%}" method="POST" class="w-25 mx-auto">
    {% csrf_token %} 
    {% include 'folders/form.html' with form=form %}
    <input type="submit" value="Edit">
</form>
{% endblock %}

characters/templates/characters/form.html
{{ form.as_p }}

characters/templates/characters/view.html
{% extends "base.html" %} 
{% load static %}

{% block extra_imports %} 
<link rel="stylesheet" href="{% static 'characters/view.css' %}">
{% endblock %}

{% block main %} 
<h1>Viewing character &quot;{{ char.name }}&quot;</h1>
<a href="{% url 'folders:view' char.folder.id %}">View folder</a>

{% if request.user.id == char.owner.id %}
<a href="{% url 'characters:edit' char.id %}">Edit</a>
<a href="{% url 'characters:delete' char.id %}">Delete</a>

{% if delete_confirmation %}
<form action="{% url 'characters:delete' char.id %}" method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete this character?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>
{% endif %}

{% if char.private %} 
<p>This character is <strong>private</strong></p>
{% else %} 
<p>This character is <strong>public</strong></p>
{% endif %}
{% endif %}

<p>Created {{ char.created }}</p>

<div id="character-view">
    <section id="basics">
        <h2>Basics:</h2>
        <p>Name: {{ char.name }}</p>
        <p>Nicknames: {{ char.nicknames }}</p>
        <p>Age: {{ char.age|default_if_none:'Unspecified' }}</p>
        <p>Sex: {{ char.sex|default_if_none:'Unspecified' }}</p>
        <p>Gender: {{ char.gender|default_if_none:'Unspecified' }}</p>
        <p>Religion: {{ char.religion }}</p>
        <p>Race: {{ char.race|default_if_none:'Unspecified' }}</p>
        <p>Species: {{ char.species|default_if_none:'Unspecified' }}</p>
        <p>Description: {{ char.description|default_if_none:'' }}</p>
    </section>

    <section id="birth">
        <h2>Birth Details:</h2>
        <p>Birthday: {{ char.birthday|default_if_none:'Unspecified' }}</p>
        <p>Birthplace: {{ char.birthplace|default_if_none:'Unspecified' }}</p>
    </section>

    <section id="physical">
        <h2>Physicality:</h2>
        <p>Blood type: {{ char.blood_type|default_if_none:'Unspecified' }}</p>

        {% if char.height %}
        <p>Height: {{ char.height }}m</p>
        {% else %} 
        <p>Height: Unspecified</p>
        {% endif %}

        {% if char.weight %}
        <p>Weight: {{ char.weight }}kg</p>
        {% else %} 
        <p>Weight: Unspecified</p>
        {% endif %}

        <p>Eye colour: {{ char.eye_colour|default_if_none:'Unspecified' }}</p>
        <p>Hair colour: {{ char.hair_colour|default_if_none:'Unspecified' }}</p>
        <p>Eyesight: {{ char.eyesight|default_if_none:'Unspecified' }}</p>
        <p>Handedness: {{ char.handedness|default_if_none:'Unspecified' }}</p>
        <p>Voice: {{ char.voice|default_if_none:'Unspecified' }}</p>
        <p>Physical description: {{ char.physical_description|default_if_none:'' }}</p>
        <p>Clothing: {{ char.clothing|default_if_none:'Unspecified' }}</p>
    </section>

    <section id="history">
        <h2>History and Relationships:</h2>
        <p>Medical history: {{ char.medical_history }}</p>
        <p>Criminal record: {{ char.criminal_record }}</p>
        <p>Education: {{ char.education|default_if_none:'Unspecified' }}</p>
        <p>Forming events: {{ char.forming_events }}</p>
        <p>Romantic history: {{ char.romance }}</p>
        <p>Employment history: {{ char.employment }}</p>
        <p>Relationships: {{ char.relationships|default_if_none:'Unspecified' }}</p>
        <p>Pets: {{ char.pets }}</p>
    </section>

    <section id="personality">
        <h2>Personality</h2>
        <p>Hopes and dreams: {{ char.hopes_and_dreams }}</p>
        <p>Fears: {{ char.fears }}</p>
        <p>Hobbies: {{ char.hobbies }}</p>
        <p>Likes: {{ char.likes }}</p>
        <p>Dislikes: {{ char.dislikes }}</p>
        <p>Personality: {{ char.personality|default_if_none:'Unspecified' }}</p>
    </section>

    <section id="misc">
        <h2>Ability:</h2>
        <p>Skills: {{ char.skills }}</p>
        <p>Weaknesses: {{ char.weaknesses }}</p>
    </section>

    <section id="tags">
        <h2>Tags:</h2>
        <p>
        {% for tag in char.tag_set.all %}
        {{ tag.tag }}, 
        {% endfor %}
        </p>
    </section>
</div>
{% endblock %}