folders/urls.py
from django.urls import path
from folders.views import *

app_name = "folders"
urlpatterns = [
    path("<int:parent>/add/", AddFolderView.as_view(), name="add"),
    path("<int:pk>/view/", DisplayFolderView.as_view(), name="view"),
    path("<int:pk>/edit/", EditFolderView.as_view(), name="edit"),
    path("<int:pk>/delete/", DeleteFolderView.as_view(), name="delete")
]

mytoyhouse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

def landing(request):
    return redirect('accounts:login')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing, name='landing'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('folders/', include('folders.urls', namespace='folders')),
    path('characters/', include('characters.urls', namespace='characters'))
]

characters/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from folders.models import Folder

# Create your models here.
class Character(models.Model):
    owner = models.ForeignKey(User, null=False, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_created=True, default=timezone.now)
    folder = models.ForeignKey(Folder, null=False, on_delete=models.CASCADE)

    # basics
    name = models.CharField(max_length=200, null=False)
    nicknames = models.CharField(max_length=200, null=True, blank=True)
    age = models.PositiveIntegerField(null=True, blank=True)
    sex = models.CharField(max_length=20, null=True, blank=True)
    gender = models.CharField(max_length=20, null=True, blank=True)
    description = models.CharField(max_length=200, null=True, blank=True)
    religion = models.CharField(max_length=100, null=True, blank=True)
    race = models.CharField(max_length=100, null=True, blank=True)
    species = models.CharField(max_length=100, null=True, blank=True)

    # birth related
    birthday = models.DateField(null=True, blank=True)
    birthplace = models.CharField(max_length=200, null=True, blank=True)

    # physical descriptions
    blood_type = models.CharField(max_length=5, null=True, blank=True)
    height = models.DecimalField(decimal_places=2, max_digits=10, null=True, blank=True)  # in meters
    weight = models.DecimalField(decimal_places=2, max_digits=10, null=True, blank=True)  # in kilograms
    eye_colour = models.CharField(max_length=50, null=True, blank=True)
    hair_colour = models.CharField(max_length=50, null=True, blank=True)
    eyesight = models.CharField(max_length=50, null=True, blank=True)
    handedness = models.CharField(max_length=20, null=True, blank=True)
    voice = models.CharField(max_length=100, null=True, blank=True)
    physical_description = models.CharField(max_length=2000, null=True, blank=True)
    clothing = models.CharField(max_length=2000, null=True, blank=True)

    # history
    medical_history = models.CharField(max_length=2000, null=True, blank=True)
    criminal_record = models.CharField(max_length=2000, null=True, blank=True)
    education = models.CharField(max_length=2000, null=True, blank=True)
    forming_events = models.CharField(max_length=2000, null=True, blank=True)
    romance = models.CharField(max_length=2000, null=True, blank=True)  # sex life? previous marriages?
    relationships = models.CharField(max_length=2000, null=True, blank=True)
    employment = models.CharField(max_length=2000, null=True, blank=True)  # employment history and current job
    pets = models.CharField(max_length=2000, null=True, blank=True)

    # personality
    hopes_and_dreams = models.CharField(max_length=2000, null=True, blank=True)
    fears = models.CharField(max_length=2000, null=True, blank=True)
    hobbies = models.CharField(max_length=2000, null=True, blank=True)
    likes = models.CharField(max_length=2000, null=True, blank=True)
    dislikes = models.CharField(max_length=2000, null=True, blank=True)
    personality = models.CharField(max_length=2000, null=True, blank=True)

    # misc
    skills = models.CharField(max_length=3000, null=True, blank=True)  # skills? superpowers?
    weaknesses = models.CharField(max_length=3000, null=True, blank=True)
    private = models.BooleanField(null=False, default=False)  # whether other people can view this character

    def __str__(self):
        return self.name
    
    def list_tags(self):
        # return a list of this character's tags as list of strings
        return list(map(str, self.tag_set.all()))


class Tag(models.Model):
    character = models.ForeignKey(Character, on_delete=models.CASCADE)
    tag = models.CharField(max_length=100, null=False)

    def __str__(self):
        return self.tag

folders/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class Folder(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    parent = models.ForeignKey("self", null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=100, null=False)
    created = models.DateTimeField(auto_created=True, default=timezone.now)
    private = models.BooleanField(null=False, default=False)  # whether other people can view this folder
    description = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.name
    
class RootFolder(Folder):
    root_owner = models.OneToOneField(User, on_delete=models.CASCADE)
    

folders/views/AddFolderView.py
from django.views.generic.edit import CreateView
from folders.models import Folder
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404

class AddFolderView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy("accounts:login")
    model = Folder
    template_name = "folders/add.html"
    fields = ["parent", "name", "description", "private"]

    def get(self, request, parent):
        # user must be the owner
        parent = get_object_or_404(Folder, id=parent)
        if parent.owner != request.user:
            return HttpResponseForbidden()
        return super().get(request, parent)
    
    def post(self, request, parent):
        # user must be the owner
        parent = get_object_or_404(Folder, id=parent)
        if parent.owner != request.user:
            return HttpResponseForbidden()
        return super().post(request, parent)
    
    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["parent"] = self.kwargs["parent"]
        return data

    def get_success_url(self) -> str:
        # open details of the new folder
        return reverse_lazy("folders:view", kwargs={"pk": self.object.id})

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)
    
    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        form.fields["parent"].queryset = self.request.user.folder_set.all()
        form.fields["parent"].initial = self.request.user.folder_set.get(id=self.kwargs["parent"])
        return form

folders/views/DeleteFolderView.py
from django.views.generic.edit import DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404
from folders.models import Folder


class DeleteFolderView(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy("accounts:login")
    model = Folder
    template_name = "folders/view.html"
    context_object_name = "folder"

    def get_success_url(self):
        return reverse_lazy("folders:view", kwargs={"pk": self.get_object().parent.id})

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["delete_confirmation"] = True
        return data

    def get(self, request, pk):
        folder = get_object_or_404(Folder, id=pk)

        # cannot delete root folder
        if folder.owner is None:
            return HttpResponseForbidden()

        # check ownership
        if folder.owner != request.user:
            return HttpResponseForbidden()
        return super().get(request, pk)

    def post(self, request, pk):
        folder = get_object_or_404(Folder, id=pk)

        # cannot delete root folder
        if folder.owner is None:
            return HttpResponseForbidden()

        # check ownership
        if folder.owner != request.user:
            return HttpResponseForbidden()
        return super().post(request, pk)

folders/views/DisplayFolderView.py
from django.views.generic.detail import DetailView
from folders.models import *
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import HttpResponseForbidden, HttpResponseNotAllowed

class DisplayFolderView(LoginRequiredMixin, DetailView):
    login_url = reverse_lazy("accounts:login")
    template_name = "folders/view.html"
    context_object_name = "folder"
    model = Folder

    def get(self, request, pk):
        # if folder is actually a root folder (root folders are always viewable)
        if self.get_object().parent is None:
            self.template_name = "folders/root.html"
            self.context_object_name = "root"

        if request.user != self.get_object().owner and self.get_object().private:
            return HttpResponseForbidden()
        
        return super().get(request, pk)
    
    def post(self, request, pk):
        return HttpResponseNotAllowed(("GET"))

folders/views/EditFolderView.py
from django.views.generic.edit import UpdateView
from folders.models import Folder
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.http import HttpResponseForbidden

class EditFolderView(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy("accounts:login")
    template_name="folders/edit.html"
    context_object_name = "folder"
    model = Folder
    fields = ["parent", "name", "description", "private"]

    def get(self, request, pk):
        # user must be the owner
        folder = self.get_object()
        if folder.owner != request.user:
            return HttpResponseForbidden()
        return super().get(request, pk)
    
    def post(self, request, pk):
        # user must be the owner
        folder = self.get_object()
        if folder.owner != request.user:
            return HttpResponseForbidden()
        return super().post(request, pk)

    def get_success_url(self) -> str:
        # open details of the new folder
        return reverse_lazy("folders:view", kwargs={"pk": self.object.id})
    
    def get_form(self, *args, **kwargs):
        form = super().get_form(*args, **kwargs)
        form.fields["parent"].queryset = self.request.user.folder_set.all().exclude(id=self.kwargs["pk"])
        form.fields["parent"].queryset = form.fields["parent"].queryset.exclude(id__in=self.get_object().folder_set.all())
        return form

folders/templates/folders/add.html
{% extends "base.html" %} 

{% block main %} 
<h1>Create new folder</h1>
<form action="{% url 'folders:add' parent%}" method="POST" class="w-25 mx-auto">
    {% csrf_token %} 
    {% include 'folders/form.html' with form=form %}
    <input type="submit" value="Create">
</form>
{% endblock %}

folders/templates/folders/details.html
{% extends "base.html" %}

{% block main %}
<h1>Viewing folder &quot;{{ folder.name }}&quot;</h1>

{% if folder.parent %}
    {% if folder.parent.parent %}
    <a href="{% url 'folders:details' folder.parent.id %}">Go back</a>
    {% else %}
    <a href="{% url 'folders:root' %}">Go back</a>
    {% endif %}
{% endif %}

<a href="{% url 'folders:add' folder.id %}">Add folder</a>
<a href="{% url 'characters:add' folder.id %}">Add character</a>
<ul>
    {% for f in folder.folder_set.all %}
    <li><a href="{% url 'folders:details' f.id %}">{{ f.name }}</a></li>
    {% endfor %}
</ul>
<section>
    <h1>Characters</h1>
    <ul>
        {% for char in folder.character_set.all %}
        <li><a href="#">{{ char.name }}</a></li>
        {% endfor %}
    </ul>
</section>
{% endblock %}

folders/templates/folders/edit.html
{% extends "base.html" %} 

{% block main %} 
<h1>Edit folder</h1>
<form action="{% url 'folders:edit' folder.id %}" method="POST" class="w-25 mx-auto">
    {% csrf_token %} 
    {% include 'folders/form.html' with form=form %}
    <input type="submit" value="Edit">
</form>
{% endblock %}

folders/templates/folders/form.html
{{ form.as_p }}

folders/templates/folders/root.html
{% extends "base.html" %}

{% block main %}
{% if request.user.id == root.owner.id %}
<h1>Your folders</h1>
<a href="{% url 'folders:add' root.id %}">Add folder</a>
{% else %} 
<h1>Viewing {{ root.owner.username }}'s folders</h1>
{% endif %}

<ul>
    {% for folder in root.folder_set.all|dictsort:'name' %}
    {% if folder.owner.id == request.user.id or not folder.private %}
    <li><a href="{% url 'folders:view' folder.id %}">{{ folder.name }}</a></li>
    {% endif %}
    {% endfor %}
</ul>
{% endblock %}

folders/templates/folders/view.html
{% extends "base.html" %}

{% block main %}
<h1>Viewing folder &quot;{{ folder.name }}&quot;</h1>

{% if folder.parent %}
    <a href="{% url 'folders:view' folder.parent.id %}">View parent folder</a>
{% endif %}

{% if request.user.id == folder.owner.id %}
<a href="{% url 'folders:add' folder.id %}">Add folder</a>
<a href="{% url 'characters:add' folder.id %}">Add character</a>
<a href="{% url 'folders:edit' folder.id %}">Edit</a>
<a href="{% url 'folders:delete' folder.id %}">Delete</a>

{% if delete_confirmation %}
<form action="{% url 'folders:delete' folder.id %}" method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete this folder?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>
{% endif %}

{% if folder.private %} 
<p>This folder is <strong>private</strong></p>
{% else %} 
<p>This folder is <strong>public</strong></p>
{% endif %}
{% endif %} 

{% if folder.description %}
<p>{{ folder.description }}</p>
{% endif %}
<p>Created {{ folder.created }}</p>

<ul>
    {% for f in folder.folder_set.all|dictsort:'name' %}
    {% if f.owner.id == request.user.id or not f.private %}
    <li><a href="{% url 'folders:view' f.id %}">{{ f.name }}</a></li>
    {% endif %}
    {% endfor %}
</ul>
<section>
    <h1>Characters</h1>
    <ul>
        {% for char in folder.character_set.all|dictsort:'name' %}
        {% if char.owner.id == request.user.id or not char.private %}
        <li><a href="{% url 'characters:view' char.id %}">{{ char.name }}</a></li>
        {% endif %}
        {% endfor %}
    </ul>
</section>
{% endblock %}