accounts/urls.py
from django.urls import path 
from accounts.views import *

app_name = "accounts"
urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("home/", HomeView.as_view(), name="home"),
    path("logout/", LogoutView.as_view(), name="logout")
]

folders/urls.py
from django.urls import path
from folders.views import *

app_name = "folders"
urlpatterns = [
    path("<int:parent>/add/", AddFolderView.as_view(), name="add"),
    path("<int:pk>/view/", DisplayFolderView.as_view(), name="view"),
    path("<int:pk>/edit/", EditFolderView.as_view(), name="edit"),
    path("<int:pk>/delete/", DeleteFolderView.as_view(), name="delete")
]

mytoyhouse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

def landing(request):
    return redirect('accounts:login')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing, name='landing'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('folders/', include('folders.urls', namespace='folders')),
    path('characters/', include('characters.urls', namespace='characters'))
]

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms/LoginForm.py
from django import forms
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField(max_length=100, required=True, error_messages={"required": "Please provide a username."})
    password = forms.CharField(min_length=8, required=True, error_messages={"required": "Please provide a password."})

accounts/forms/UserForm.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.Form):
    username = forms.CharField(max_length=100, required=True, error_messages={"required": "Please provide a username."})
    pass1 = forms.CharField(min_length=8, required=True)
    pass2 = forms.CharField(min_length=8, required=True, error_messages={"required": "You must confirm your password."})
    
    def clean_username(self):
        username = self.cleaned_data.get("username").strip()
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError("That username is taken.")
        return username

    def clean_pass2(self):
        pass1 = self.cleaned_data.get("pass1")
        pass2 = self.cleaned_data.get("pass2")

        if pass1 != pass2:
            raise forms.ValidationError("Your passwords do not match.")
        return pass2

accounts/views/HomeView.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View 
from django.urls import reverse_lazy
from django.shortcuts import render
from django.http import HttpResponseNotAllowed

class HomeView(LoginRequiredMixin, View):
    login_url = reverse_lazy("accounts:login")
    
    def get(self, request):
        return render(request, "accounts/home.html")
    
    def post(self, request):
        return HttpResponseNotAllowed(("GET"))

accounts/views/LoginView.py
from django.views.generic.edit import FormView
from accounts.forms import LoginForm
from django.urls import reverse_lazy
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect

class LoginView(FormView):
    form_class = LoginForm
    template_name = "accounts/login.html"
    success_url = reverse_lazy("accounts:home")

    def get(self, request):
        if request.user.is_authenticated:
            return redirect("accounts:home")
        return super().get(request)

    def form_valid(self, form):
        username = form.cleaned_data["username"]
        password = form.cleaned_data["password"]

        user = authenticate(self.request, username=username, password=password)
        if user is None:
            print("bruh")
            form.add_error("username", "Username/password combination is not correct")
            return super().form_invalid(form)
        else:
            login(self.request, user)
            return super().form_valid(form)

accounts/views/LogoutView.py
from django.views import View 
from django.http import HttpResponseNotAllowed
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import redirect

class LogoutView(LoginRequiredMixin, View):
    login_url = reverse_lazy("accounts:login")
    def get(self, request):
        logout(request)
        return redirect("accounts:login")
    
    def post(self, request):
        return HttpResponseNotAllowed(("GET"))

accounts/views/PlaceholderView.py
from django.views import View
from django.shortcuts import render

class PlaceholderView(View):
    def get(self, request):
        return render(request, "accounts/base.html")

accounts/views/SignUpView.py
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from accounts.forms import UserForm
from django.contrib.auth.models import User
from folders.models import RootFolder

class SignUpView(FormView):
    template_name = "accounts/signup.html"
    success_url = reverse_lazy("accounts:login")
    form_class = UserForm

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["title"] = "Sign Up"
        return data
    
    def form_valid(self, form):
        # create the user
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("pass1")
        user = User.objects.create_user(username=username, password=password)
        user.save()

        # create the root directory for that user
        root = RootFolder.objects.create(root_owner=user, owner=user, name="root")
        root.save()
        
        return super().form_valid(form)

accounts/templates/accounts/home.html
{% extends "base.html" %} 

{% block main %} 
<h1>Welcome, {{ request.user.username }}!</h1>
<a href="{% url 'folders:view' request.user.rootfolder.id %}">view your folders</a>
<a href="#">view all your characters</a>
<a href="{% url 'accounts:logout' %}">Log out</a>
{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %} 

{% block main %} 
<form action="{% url 'accounts:login' %}" method="POST" class="mx-auto w-25">
    {% csrf_token %} 
    
    <p>
        {% if form.username.errors %} 
        <div class="errors">{{ form.username.errors }}</div>
        {% endif %}
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" value="{{ form.username.value|default_if_none:'' }}">
    </p>
    <p>
        {% if form.password.errors %} 
        <div class="errors">{{ form.password.errors }}</div>
        {% endif %}
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" value="">
    </p>

    <input type="submit" value="Login">
</form>
<a href="{% url 'accounts:signup' %}">Sign up instead</a>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %} 

{% block main %} 

<form action="{% url 'accounts:signup' %}" method="POST" class="mx-auto w-25">
    {% csrf_token %} 
    
    <p>
        {% if form.username.errors %} 
        <div class="errors">{{ form.username.errors }}</div>
        {% endif %}
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" value="{{ form.username.value|default_if_none:'' }}">
    </p>
    <p>
        {% if form.pass1.errors %} 
        <div class="errors">{{ form.pass1.errors }}</div>
        {% endif %}
        <label for="password1">Password:</label>
        <input type="password" id="password1" name="pass1" value="">
    </p>
    <p>
        {% if form.pass2.errors %} 
        <div class="errors">{{ form.pass2.errors }}</div>
        {% endif %}
        <label for="password2">Confirm password:</label>
        <input type="password" id="password2" name="pass2" value="">
    </p>

    <input type="submit" value="Sign up">
</form>
{% endblock %}