accounts/urls.py
from django.urls import path 
from accounts.views import *

app_name = "accounts"
urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("home/", HomeView.as_view(), name="home"),
    path("logout/", LogoutView.as_view(), name="logout")
]

folders/urls.py
from django.urls import path
from folders.views import *

app_name = "folders"
urlpatterns = [
    path("<int:parent>/add/", AddFolderView.as_view(), name="add"),
    path("<int:pk>/view/", DisplayFolderView.as_view(), name="view"),
    path("<int:pk>/edit/", EditFolderView.as_view(), name="edit"),
    path("<int:pk>/delete/", DeleteFolderView.as_view(), name="delete")
]

mytoyhouse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

def landing(request):
    return redirect('accounts:login')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing, name='landing'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('folders/', include('folders.urls', namespace='folders')),
    path('characters/', include('characters.urls', namespace='characters'))
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <meta name="author" content="Andy Wang">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <link href="{% static 'style.css' %}" rel="stylesheet">
    {% block extra_imports %} 
    {% endblock %}
</head>
<body>
    <div id="page-container">
        <div id="content-wrap">
            <header>
                <a href="{% url 'accounts:home' %}">homepage</a>
            </header>
            <main>
                {% block main %} 
                {% endblock %}
            </main>
        </div>
        <footer>
            i'm a footer!
        </footer>
    </div>
</body>